[package]
name = "hydroper_jet_compiler"
version = "0.1.1"
edition = "2021"
authors = ["hydroper <matheusdiasdesouzads@gmail.com>"]
repository = "https://github.com/hydroper-jet/compiler"
keywords = ["hydroper-jet", "compiler"]
description = "Hydroper Jet Language Compiler"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hydroper_jet_compiler"
path = "lib.rs"

[dependencies]
bitflags = { version = "2.4.1", features = ["serde"] }
clap = { version = "4.4.8", features = ["derive"] }
file_paths = "1.0.0"
conv = "0.3.3"
late_format = "1.0.0"
maplit = "1.0.2"
num-derive = "0.4.1"
num-traits = "0.2.17"
lazy-regex = "3.0.2"
lazy_static = "1.4.0"
unicode-general-category = "0.6.0"
by_address = "1.1.0"
serde = { version = "1.0.192", features = ["rc", "derive"] }
serde_json = "1.0.108"
